export const countryCodes = [
  { id: 1, name: 'Afghanistan', code: '+93', flag: '🇦🇫' },
  { id: 2, name: 'Albania', code: '+355', flag: '🇦🇱' },
  { id: 3, name: 'Algeria', code: '+213', flag: '🇩🇿' },
  { id: 4, name: 'Andorra', code: '+376', flag: '🇦🇩' },
  { id: 5, name: 'Angola', code: '+244', flag: '🇦🇴' },
  { id: 6, name: 'Argentina', code: '+54', flag: '🇦🇷' },
  { id: 7, name: 'Armenia', code: '+374', flag: '🇦🇲' },
  { id: 8, name: 'Australia', code: '+61', flag: '🇦🇺' },
  { id: 9, name: 'Austria', code: '+43', flag: '🇦🇹' },
  { id: 10, name: 'Azerbaijan', code: '+994', flag: '🇦🇿' },
  { id: 11, name: 'Bahamas', code: '+1-242', flag: '🇧🇸' },
  { id: 12, name: 'Bahrain', code: '+973', flag: '🇧🇭' },
  { id: 13, name: 'Bangladesh', code: '+880', flag: '🇧🇩' },
  { id: 14, name: 'Barbados', code: '+1-246', flag: '🇧🇧' },
  { id: 15, name: 'Belarus', code: '+375', flag: '🇧🇾' },
  { id: 16, name: 'Belgium', code: '+32', flag: '🇧🇪' },
  { id: 17, name: 'Belize', code: '+501', flag: '🇧🇿' },
  { id: 18, name: 'Benin', code: '+229', flag: '🇧🇯' },
  { id: 19, name: 'Bhutan', code: '+975', flag: '🇧🇹' },
  { id: 20, name: 'Bolivia', code: '+591', flag: '🇧🇴' },
  { id: 21, name: 'Bosnia and Herzegovina', code: '+387', flag: '🇧🇦' },
  { id: 22, name: 'Botswana', code: '+267', flag: '🇧🇼' },
  { id: 23, name: 'Brazil', code: '+55', flag: '🇧🇷' },
  { id: 24, name: 'Brunei', code: '+673', flag: '🇧🇳' },
  { id: 25, name: 'Bulgaria', code: '+359', flag: '🇧🇬' },
  { id: 26, name: 'Burkina Faso', code: '+226', flag: '🇧🇫' },
  { id: 27, name: 'Burundi', code: '+257', flag: '🇧🇮' },
  { id: 28, name: 'Cambodia', code: '+855', flag: '🇰🇭' },
  { id: 29, name: 'Cameroon', code: '+237', flag: '🇨🇲' },
  { id: 30, name: 'Canada', code: '+1', flag: '🇨🇦' },
  { id: 31, name: 'Cape Verde', code: '+238', flag: '🇨🇻' },
  { id: 32, name: 'Central African Republic', code: '+236', flag: '🇨🇫' },
  { id: 33, name: 'Chad', code: '+235', flag: '🇹🇩' },
  { id: 34, name: 'Chile', code: '+56', flag: '🇨🇱' },
  { id: 35, name: 'China', code: '+86', flag: '🇨🇳' },
  { id: 36, name: 'Colombia', code: '+57', flag: '🇨🇴' },
  { id: 37, name: 'Comoros', code: '+269', flag: '🇰🇲' },
  { id: 38, name: 'Congo', code: '+242', flag: '🇨🇬' },
  { id: 39, name: 'Costa Rica', code: '+506', flag: '🇨🇷' },
  { id: 40, name: 'Croatia', code: '+385', flag: '🇭🇷' },
  { id: 41, name: 'Cuba', code: '+53', flag: '🇨🇺' },
  { id: 42, name: 'Cyprus', code: '+357', flag: '🇨🇾' },
  { id: 43, name: 'Czech Republic', code: '+420', flag: '🇨🇿' },
  { id: 44, name: 'Denmark', code: '+45', flag: '🇩🇰' },
  { id: 45, name: 'Djibouti', code: '+253', flag: '🇩🇯' },
  { id: 46, name: 'Dominica', code: '+1-767', flag: '🇩🇲' },
  { id: 47, name: 'Dominican Republic', code: '+1-809', flag: '🇩🇴' },
  { id: 48, name: 'Ecuador', code: '+593', flag: '🇪🇨' },
  { id: 49, name: 'Egypt', code: '+20', flag: '🇪🇬' },
  { id: 50, name: 'El Salvador', code: '+503', flag: '🇸🇻' },
  { id: 51, name: 'Equatorial Guinea', code: '+240', flag: '🇬🇶' },
  { id: 52, name: 'Eritrea', code: '+291', flag: '🇪🇷' },
  { id: 53, name: 'Estonia', code: '+372', flag: '🇪🇪' },
  { id: 54, name: 'Ethiopia', code: '+251', flag: '🇪🇹' },
  { id: 55, name: 'Fiji', code: '+679', flag: '🇫🇯' },
  { id: 56, name: 'Finland', code: '+358', flag: '🇫🇮' },
  { id: 57, name: 'France', code: '+33', flag: '🇫🇷' },
  { id: 58, name: 'Gabon', code: '+241', flag: '🇬🇦' },
  { id: 59, name: 'Gambia', code: '+220', flag: '🇬🇲' },
  { id: 60, name: 'Georgia', code: '+995', flag: '🇬🇪' },
  { id: 61, name: 'Germany', code: '+49', flag: '🇩🇪' },
  { id: 62, name: 'Ghana', code: '+233', flag: '🇬🇭' },
  { id: 63, name: 'Greece', code: '+30', flag: '🇬🇷' },
  { id: 64, name: 'Grenada', code: '+1-473', flag: '🇬🇩' },
  { id: 65, name: 'Guatemala', code: '+502', flag: '🇬🇹' },
  { id: 66, name: 'Guinea', code: '+224', flag: '🇬🇳' },
  { id: 67, name: 'Guinea-Bissau', code: '+245', flag: '🇬🇼' },
  { id: 68, name: 'Guyana', code: '+592', flag: '🇬🇾' },
  { id: 69, name: 'Haiti', code: '+509', flag: '🇭🇹' },
  { id: 70, name: 'Honduras', code: '+504', flag: '🇭🇳' },
  { id: 71, name: 'Hong Kong', code: '+852', flag: '🇭🇰' },
  { id: 72, name: 'Hungary', code: '+36', flag: '🇭🇺' },
  { id: 73, name: 'Iceland', code: '+354', flag: '🇮🇸' },
  { id: 74, name: 'India', code: '+91', flag: '🇮🇳' },
  { id: 75, name: 'Indonesia', code: '+62', flag: '🇮🇩' },
  { id: 76, name: 'Iran', code: '+98', flag: '🇮🇷' },
  { id: 77, name: 'Iraq', code: '+964', flag: '🇮🇶' },
  { id: 78, name: 'Ireland', code: '+353', flag: '🇮🇪' },
  { id: 79, name: 'Israel', code: '+972', flag: '🇮🇱' },
  { id: 80, name: 'Italy', code: '+39', flag: '🇮🇹' },
  { id: 81, name: 'Jamaica', code: '+1-876', flag: '🇯🇲' },
  { id: 82, name: 'Japan', code: '+81', flag: '🇯🇵' },
  { id: 83, name: 'Jordan', code: '+962', flag: '🇯🇴' },
  { id: 84, name: 'Kazakhstan', code: '+7', flag: '🇰🇿' },
  { id: 85, name: 'Kenya', code: '+254', flag: '🇰🇪' },
  { id: 86, name: 'Kiribati', code: '+686', flag: '🇰🇮' },
  { id: 87, name: 'Kosovo', code: '+383', flag: '🇽🇰' },
  { id: 88, name: 'Kuwait', code: '+965', flag: '🇰🇼' },
  { id: 89, name: 'Kyrgyzstan', code: '+996', flag: '🇰🇬' },
  { id: 90, name: 'Laos', code: '+856', flag: '🇱🇦' },
  { id: 91, name: 'Latvia', code: '+371', flag: '🇱🇻' },
  { id: 92, name: 'Lebanon', code: '+961', flag: '🇱🇧' },
  { id: 93, name: 'Lesotho', code: '+266', flag: '🇱🇸' },
  { id: 94, name: 'Liberia', code: '+231', flag: '🇱🇷' },
  { id: 95, name: 'Libya', code: '+218', flag: '🇱🇾' },
  { id: 96, name: 'Liechtenstein', code: '+423', flag: '🇱🇮' },
  { id: 97, name: 'Lithuania', code: '+370', flag: '🇱🇹' },
  { id: 98, name: 'Luxembourg', code: '+352', flag: '🇱🇺' },
  { id: 99, name: 'Macao', code: '+853', flag: '🇲🇴' },
  { id: 100, name: 'Madagascar', code: '+261', flag: '🇲🇬' },
  { id: 101, name: 'Malawi', code: '+265', flag: '🇲🇼' },
  { id: 102, name: 'Malaysia', code: '+60', flag: '🇲🇾' },
  { id: 103, name: 'Maldives', code: '+960', flag: '🇲🇻' },
  { id: 104, name: 'Mali', code: '+223', flag: '🇲🇱' },
  { id: 105, name: 'Malta', code: '+356', flag: '🇲🇹' },
  { id: 106, name: 'Marshall Islands', code: '+692', flag: '🇲🇭' },
  { id: 107, name: 'Mauritania', code: '+222', flag: '🇲🇷' },
  { id: 108, name: 'Mauritius', code: '+230', flag: '🇲🇺' },
  { id: 109, name: 'Mexico', code: '+52', flag: '🇲🇽' },
  { id: 110, name: 'Micronesia', code: '+691', flag: '🇫🇲' },
  { id: 111, name: 'Moldova', code: '+373', flag: '🇲🇩' },
  { id: 112, name: 'Monaco', code: '+377', flag: '🇲🇨' },
  { id: 113, name: 'Mongolia', code: '+976', flag: '🇲🇳' },
  { id: 114, name: 'Montenegro', code: '+382', flag: '🇲🇪' },
  { id: 115, name: 'Morocco', code: '+212', flag: '🇲🇦' },
  { id: 116, name: 'Mozambique', code: '+258', flag: '🇲🇿' },
  { id: 117, name: 'Myanmar', code: '+95', flag: '🇲🇲' },
  { id: 118, name: 'Namibia', code: '+264', flag: '🇳🇦' },
  { id: 119, name: 'Nauru', code: '+674', flag: '🇳🇷' },
  { id: 120, name: 'Nepal', code: '+977', flag: '🇳🇵' },
  { id: 121, name: 'Netherlands', code: '+31', flag: '🇳🇱' },
  { id: 122, name: 'New Zealand', code: '+64', flag: '🇳🇿' },
  { id: 123, name: 'Nicaragua', code: '+505', flag: '🇳🇮' },
  { id: 124, name: 'Niger', code: '+227', flag: '🇳🇪' },
  { id: 125, name: 'Nigeria', code: '+234', flag: '🇳🇬' },
  { id: 126, name: 'North Korea', code: '+850', flag: '🇰🇵' },
  { id: 127, name: 'North Macedonia', code: '+389', flag: '🇲🇰' },
  { id: 128, name: 'Norway', code: '+47', flag: '🇳🇴' },
  { id: 129, name: 'Oman', code: '+968', flag: '🇴🇲' },
  { id: 130, name: 'Pakistan', code: '+92', flag: '🇵🇰' },
  { id: 131, name: 'Palau', code: '+680', flag: '🇵🇼' },
  { id: 132, name: 'Palestine', code: '+970', flag: '🇵🇸' },
  { id: 133, name: 'Panama', code: '+507', flag: '🇵🇦' },
  { id: 134, name: 'Papua New Guinea', code: '+675', flag: '🇵🇬' },
  { id: 135, name: 'Paraguay', code: '+595', flag: '🇵🇾' },
  { id: 136, name: 'Peru', code: '+51', flag: '🇵🇪' },
  { id: 137, name: 'Philippines', code: '+63', flag: '🇵🇭' },
  { id: 138, name: 'Poland', code: '+48', flag: '🇵🇱' },
  { id: 139, name: 'Portugal', code: '+351', flag: '🇵🇹' },
  { id: 140, name: 'Qatar', code: '+974', flag: '🇶🇦' },
  { id: 141, name: 'Romania', code: '+40', flag: '🇷🇴' },
  { id: 142, name: 'Russia', code: '+7', flag: '🇷🇺' },
  { id: 143, name: 'Rwanda', code: '+250', flag: '🇷🇼' },
  { id: 144, name: 'Saint Kitts and Nevis', code: '+1-869', flag: '🇰🇳' },
  { id: 145, name: 'Saint Lucia', code: '+1-758', flag: '🇱🇨' },
  { id: 146, name: 'Saint Vincent and the Grenadines', code: '+1-784', flag: '🇻🇨' },
  { id: 147, name: 'Samoa', code: '+685', flag: '🇼🇸' },
  { id: 148, name: 'San Marino', code: '+378', flag: '🇸🇲' },
  { id: 149, name: 'Sao Tome and Principe', code: '+239', flag: '🇸🇹' },
  { id: 150, name: 'Saudi Arabia', code: '+966', flag: '🇸🇦' },
  { id: 151, name: 'Senegal', code: '+221', flag: '🇸🇳' },
  { id: 152, name: 'Serbia', code: '+381', flag: '🇷🇸' },
  { id: 153, name: 'Seychelles', code: '+248', flag: '🇸🇨' },
  { id: 154, name: 'Sierra Leone', code: '+232', flag: '🇸🇱' },
  { id: 155, name: 'Singapore', code: '+65', flag: '🇸🇬' },
  { id: 156, name: 'Slovakia', code: '+421', flag: '🇸🇰' },
  { id: 157, name: 'Slovenia', code: '+386', flag: '🇸🇮' },
  { id: 158, name: 'Solomon Islands', code: '+677', flag: '🇸🇧' },
  { id: 159, name: 'Somalia', code: '+252', flag: '🇸🇴' },
  { id: 160, name: 'South Africa', code: '+27', flag: '🇿🇦' },
  { id: 161, name: 'South Korea', code: '+82', flag: '🇰🇷' },
  { id: 162, name: 'South Sudan', code: '+211', flag: '🇸🇸' },
  { id: 163, name: 'Spain', code: '+34', flag: '🇪🇸' },
  { id: 164, name: 'Sri Lanka', code: '+94', flag: '🇱🇰' },
  { id: 165, name: 'Sudan', code: '+249', flag: '🇸🇩' },
  { id: 166, name: 'Suriname', code: '+597', flag: '🇸🇷' },
  { id: 167, name: 'Sweden', code: '+46', flag: '🇸🇪' },
  { id: 168, name: 'Switzerland', code: '+41', flag: '🇨🇭' },
  { id: 169, name: 'Syria', code: '+963', flag: '🇸🇾' },
  { id: 170, name: 'Taiwan', code: '+886', flag: '🇹🇼' },
  { id: 171, name: 'Tajikistan', code: '+992', flag: '🇹🇯' },
  { id: 172, name: 'Tanzania', code: '+255', flag: '🇹🇿' },
  { id: 173, name: 'Thailand', code: '+66', flag: '🇹🇭' },
  { id: 174, name: 'Timor-Leste', code: '+670', flag: '🇹🇱' },
  { id: 175, name: 'Togo', code: '+228', flag: '🇹🇬' },
  { id: 176, name: 'Tonga', code: '+676', flag: '🇹🇴' },
  { id: 177, name: 'Trinidad and Tobago', code: '+1-868', flag: '🇹🇹' },
  { id: 178, name: 'Tunisia', code: '+216', flag: '🇹🇳' },
  { id: 179, name: 'Turkey', code: '+90', flag: '🇹🇷' },
  { id: 180, name: 'Turkmenistan', code: '+993', flag: '🇹🇲' },
  { id: 181, name: 'Tuvalu', code: '+688', flag: '🇹🇻' },
  { id: 182, name: 'Uganda', code: '+256', flag: '🇺🇬' },
  { id: 183, name: 'Ukraine', code: '+380', flag: '🇺🇦' },
  { id: 184, name: 'United Arab Emirates', code: '+971', flag: '🇦🇪' },
  { id: 185, name: 'United Kingdom', code: '+44', flag: '🇬🇧' },
  { id: 186, name: 'United States', code: '+1', flag: '🇺🇸' },
  { id: 187, name: 'Uruguay', code: '+598', flag: '🇺🇾' },
  { id: 188, name: 'Uzbekistan', code: '+998', flag: '🇺🇿' },
  { id: 189, name: 'Vanuatu', code: '+678', flag: '🇻🇺' },
  { id: 190, name: 'Vatican City', code: '+379', flag: '🇻🇦' },
  { id: 191, name: 'Venezuela', code: '+58', flag: '🇻🇪' },
  { id: 192, name: 'Vietnam', code: '+84', flag: '🇻🇳' },
  { id: 193, name: 'Yemen', code: '+967', flag: '🇾🇪' },
  { id: 194, name: 'Zambia', code: '+260', flag: '🇿🇲' },
  { id: 195, name: 'Zimbabwe', code: '+263', flag: '🇿🇼' }
];
